-- AlterEnum
ALTER TYPE "PromptType" ADD VALUE IF NOT EXISTS 'REWRITE_VORKNEWS';
ALTER TYPE "PromptType" ADD VALUE IF NOT EXISTS 'SOCIAL_COPY';

-- AlterTable
ALTER TABLE "Target" ALTER COLUMN "email" DROP NOT NULL;
ALTER TABLE "Target" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'EMAIL';
ALTER TABLE "Target" ADD COLUMN IF NOT EXISTS "config" JSONB;
